version: '3'
services:
    postgresdb:
        image: pgrouting/pgrouting:${PG_VERSION}
        container_name: ${PG_NAME}
        env_file:
            - ".env"
        environment:
            POSTGRES_PASSWORD: ${PG_PASSWORD}
        ports:
            - '25432:5432'
        volumes:
            - "./data/postgresql/data:/var/lib/postgresql/data"
    
    web:
        image: nginx:alpine
        container_name: ${NGINX_NAME}
        volumes:
            - "./apps/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./apps/ssl:/etc/ssl"
            - "./html:/var/www/html"
            - "./apps/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
            #- "./datafile:/opt/datafile"
        ports:
            - "280:80"
            - "2443:443"
        stdin_open: true
        tty: true
        environment:
            - NGINX_HOST=${NGINX_HOST}
        command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        restart: always
        depends_on:
            - php
            - postgresdb
    php:
        image: nanoninja/php-fpm:${PHP_VERSION}
        container_name: ${PHP_NAME}
        restart: always
        volumes:
            - "./apps/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./html:/var/www/html"