version: '3'
services:
    geoserver:
        image: geonode/geoserver:${GEO_VERSION}
        container_name: ${GEO_NAME}
        restart: always
        env_file:
            - ".env"
        links:
            - postgresdb
        ports:
          - "28080:8080"
        volumes:
          #- /var/run/docker.sock:/var/run/docker.sock
          - "./data/geoserver/data:/geoserver_data/data"
          - "//var/run/docker.sock:/var/run/docker.sock"
          - "./apps/tomcat/manager/context.xml:/usr/local/tomcat/webapps/manager/META-INF/context.xml"
          - "./apps/tomcat/conf/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml"
          - "./apps/tomcat/conf/context.xml:/usr/local/tomcat/conf/context.xml"
        environment:
        #  - DOCKERHOST
        #  - GEONODE_HOST_IP
        #  - PUBLIC_PORT=80
        #  - DOCKER_HOST_IP
          - DJANGO_URL=http://localhost/
    postgresdb:
        image: pgrouting/pgrouting:${PG_VERSION}
        container_name: ${PG_NAME}
        env_file:
            - ".env"
        environment:
            POSTGRES_PASSWORD: ${PG_PASSWORD}
        ports:
            - '25432:5432'
        volumes:
            - "./data/postgresql/data:/var/lib/postgresql/data"
    
    web:
        image: nginx:alpine
        container_name: ${NGINX_NAME}
        volumes:
            - "./apps/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./apps/ssl:/etc/ssl"
            - "./html:/var/www/html"
            - "./apps/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
            #- "./datafile:/opt/datafile"
        ports:
            - "280:80"
            - "2443:443"
        stdin_open: true
        tty: true
        environment:
            - NGINX_HOST=${NGINX_HOST}
            - GEO_NAME=${GEO_NAME}
        command: /bin/sh -c "envsubst '$$NGINX_HOST,$$GEO_NAME' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        restart: always
        depends_on:
            - php
            - postgresdb
    php:
        image: nanoninja/php-fpm:${PHP_VERSION}
        container_name: ${PHP_NAME}
        restart: always
        volumes:
            - "./apps/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./html:/var/www/html"